<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Comandos\" />
    <Folder Include="Hadlers\" />
    <Folder Include="Consultas\" />
    <Folder Include="Dto\" />
  </ItemGroup>

</Project>
